### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abaneSebiane** [TheoPARISOT/ProjetGitESGI_LaMaison#25]
**Describe the bug**
There is a leak on the canalisation 

**Expected behavior**
I was taking a tour of the construction site after the plumber said goodbye when suddenly I saw a lot of water pouring from the ground

**Additional context**
you need to fix that guys or i will lose my house !!!!!

**Comment by Abane-S** [comment]
it's good, I took care of it, fixed the problem and merged into dev 😶‍🌫️

**Comment by abaneSebiane** [comment]
it's good, I took care of it, fixed the problem and merged into dev 😶‍🌫️
